config/routes.rb
Rails.application.routes.draw do
  root to: "articles#index"

  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true
    validates :body, presence: true

    default_scope {order(created_at: :desc)}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from ActiveRecord::RecordNotFound, with: :resources_not_found

  protected

    def resources_not_found
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show,:update,:destroy]


  def index
    @articles = Article.all
  end

  
  def new
    @article = Article.new
  end
  

  def create
    @article = Article.new(article_params)  
    if @article.save
      flash[:success] = "Article has been create"
      redirect_to articles_path
    else
      flash.now[:danger] = "The article was not created"
      render :new
    end
  end 

  def show
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article has been updated"
      redirect_to articles_path
    else
      flash.now[:danger] = "The article was not updated"
      render :show
    end  
  end

  def destroy
    if @article.destroy
      flash[:success] = "Article has been deleted"
      redirect_to articles_path
    else
      flash.now[:danger] = "The article was not deleted"
      render :show
    end  
  end
  
  protected
    def resources_not_found
      message = "The article you are looking for could not be found"
      flash[:alert] = message
      redirect_to root_path
    end

  private
    def set_article
      @article = Article.find(params[:id])  
    end
    
    def article_params
      params.require(:article).permit(:title,:body)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<% if @articles.empty?%>
    <h1 id="no-articles">No Articles Created</h1>
<%else%>
    <% @articles.each do |art| %>
        <div class="well well-lg">
            <div class="article-title">
                <%= link_to art.title, article_path(art)%>
            </div>
            <div class="article-body">
                <%= truncate(art.body, length: 500) %>
            </div>
        </div>
    <% end %>
<%end%>

app/views/articles/new.html.erb
<h3 class="text-center">Adding new articles</h3>
    <div class="col-md-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <% if @article.errors.any? %>
            <div class="panel panel-danger col-md-offset-1">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(@article.errors.count, "error") %>
                        prohibited this article from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% @article.errors.full_messages.each do |msg|%>              
                            <li>
                                <%=msg %>
                            </li>
                            <% end %>
                        </ul>      
                    </div>
                </div>
            </div>
            <% end %>
            <div class="form-group">
                <div class="control-label col-md-1">
                    <%= f.label :title %>
                </div>           
                <div class="col-md-11">
                    <%= f.text_field :title, class:"form-control",placeholder: "Title of Article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-1">
                    <%= f.label :body %>
                </div>           
                <div class="col-md-11">
                    <%= f.text_area :body, rows:10, class:"form-control",placeholder: "Body of Article"%>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-1 col-md-11">
                    <%= f.submit class: 'btn btn-primary btn-lg pull-right'%>
                </div>           
            </div>
        <%end%>
    </div>
</div>

app/views/articles/show.html.erb
<h3 class="text-center">Edit the article</h3>
    <div class="col-md-12">
        <%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <% if @article.errors.any? %>
            <div class="panel panel-danger col-md-offset-1">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        <%= pluralize(@article.errors.count, "error") %>
                        prohibited this article from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% @article.errors.full_messages.each do |msg|%>              
                            <li>
                                <%=msg %>
                            </li>
                            <% end %>
                        </ul>      
                    </div>
                </div>
            </div>
            <% end %>
            <div class="form-group">
                <div class="control-label col-md-1">
                    <%= f.label :title %>
                </div>           
                <div class="col-md-11">
                    <%= f.text_field :title, class:"form-control",placeholder: "Title of Article", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-1">
                    <%= f.label :body %>
                </div>           
                <div class="col-md-11">
                    <%= f.text_area :body, rows:10, class:"form-control",placeholder: "Body of Article"%>
                </div>
            </div>

            <div class="form-group-delete-update">
                <div class="col-md-offset-1 col-md-11">
                    <%= link_to "Delete Article",article_path(@article), method: :delete,
                    data: {confirm: "Are you sure you must to delete this article?"},                    
                    class: 'btn btn-primary btn-lg pull-left', id:"delete-article-btn"%>
                    
                    <%= f.submit class: 'btn btn-primary btn-lg pull-right'%>
                </div>           
            </div>
        <%end%>
    </div>
</div>
            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <header role="banner">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <!-- Brand -->
        <a class="navbar-brand" href="/">Demo</a>
        <%= link_to "New Article", new_article_path , class: "navbar-brand", id:"new-article-btn"%>
    </nav>
  </header>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-eval' => false %>

</head>
<body>  
  <div class="container">
    <div class="row">
      <div class="col-md-12">
          <% flash.each do |key,message| %>
            <div class="text-center alert alert-<%= key == 'notice'? 'sucess': 'danger' %>">
              <%=message%>
            </div>    
          <%end%>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>